#[allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

    // mlua compability for Option<fn(...)> callbacks
    pub type lua_CFunction = unsafe extern "C-unwind" fn(L: *mut lua_State) -> ::core::ffi::c_int;
    pub type lua_Alloc = unsafe extern "C" fn(
        ud: *mut ::core::ffi::c_void,
        ptr: *mut ::core::ffi::c_void,
        osize: usize,
        nsize: usize,
    ) -> *mut ::core::ffi::c_void;
    pub type lua_Hook = unsafe extern "C-unwind" fn(L: *mut lua_State, ar: *mut lua_Debug);

    // redefine lua_Debug to avoid bindgen making it opaque
    #[repr(C)]
    pub struct lua_Debug {
        pub event: ::core::ffi::c_int,
        pub name: *const ::core::ffi::c_char,
        pub namewhat: *const ::core::ffi::c_char,
        pub what: *const ::core::ffi::c_char,
        pub source: *const ::core::ffi::c_char,
        pub currentline: ::core::ffi::c_int,
        pub linedefined: ::core::ffi::c_int,
        pub lastlinedefined: ::core::ffi::c_int,
        pub nups: ::core::ffi::c_uchar,
        pub nparams: ::core::ffi::c_uchar,
        pub isvararg: ::core::ffi::c_char,
        pub istailcall: ::core::ffi::c_char,
        pub short_src: [::core::ffi::c_char; 60usize],
        pub i_ci: *mut ::core::ffi::c_void,
    }

    // lua_Writer is blocklisted so we can declare it without Option (non-nullable in mlua usage)
    pub type lua_Writer = unsafe extern "C-unwind" fn(
        L: *mut lua_State,
        p: *const ::core::ffi::c_void,
        sz: usize,
        ud: *mut ::core::ffi::c_void,
    ) -> ::core::ffi::c_int;
    pub type lua_KFunction = ::core::option::Option<
        unsafe extern "C-unwind" fn(
            L: *mut lua_State,
            status: ::core::ffi::c_int,
            ctx: lua_KContext,
        ) -> ::core::ffi::c_int,
    >;
}
#[cfg(feature = "baremetal")]
mod libc;

pub use bindings::*;

use core::ffi::{CStr, c_char, c_int, c_void};
use core::ptr;

// Constants not generated by bindgen (mlua-specific additions)

pub const LUA_MAX_UPVALUES: c_int = 255;
pub const LUA_TRACEBACK_STACK: c_int = 11;

#[rustfmt::skip]
pub const SYS_MIN_ALIGN: usize = if cfg!(any(
    all(target_arch = "riscv32", any(target_os = "espidf", target_os = "zkvm")),
    all(target_arch = "xtensa", target_os = "espidf"),
)) {
    4
} else if cfg!(any(
    target_arch = "x86",
    target_arch = "arm",
    target_arch = "m68k",
    target_arch = "csky",
    target_arch = "loongarch32",
    target_arch = "mips",
    target_arch = "mips32r6",
    target_arch = "powerpc",
    target_arch = "powerpc64",
    target_arch = "sparc",
    target_arch = "wasm32",
    target_arch = "hexagon",
    target_arch = "riscv32",
    target_arch = "xtensa",
)) {
    8
} else if cfg!(any(
    target_arch = "x86_64",
    target_arch = "aarch64",
    target_arch = "arm64ec",
    target_arch = "loongarch64",
    target_arch = "mips64",
    target_arch = "mips64r6",
    target_arch = "s390x",
    target_arch = "sparc64",
    target_arch = "riscv64",
    target_arch = "wasm64",
)) {
    16
} else {
    panic!("no value for SYS_MIN_ALIGN")
};

// String constants — bindgen generates these as &[u8] but mlua expects *const c_char
pub const LUA_COLIBNAME: *const c_char = c"coroutine".as_ptr();
pub const LUA_TABLIBNAME: *const c_char = c"table".as_ptr();
pub const LUA_IOLIBNAME: *const c_char = c"io".as_ptr();
pub const LUA_OSLIBNAME: *const c_char = c"os".as_ptr();
pub const LUA_STRLIBNAME: *const c_char = c"string".as_ptr();
pub const LUA_BITLIBNAME: *const c_char = c"bit32".as_ptr();
pub const LUA_MATHLIBNAME: *const c_char = c"math".as_ptr();
pub const LUA_DBLIBNAME: *const c_char = c"debug".as_ptr();
pub const LUA_LOADLIBNAME: *const c_char = c"package".as_ptr();
pub const LUA_LOADED_TABLE: *const c_char = c"_LOADED".as_ptr();
pub const LUA_PRELOAD_TABLE: *const c_char = c"_PRELOAD".as_ptr();
pub const LUA_UTF8LIBNAME: *const c_char = c"utf8".as_ptr();

// LUA_RIDX_* constants are i32 from bindgen but lua_rawgeti/etc expect lua_Integer (i64)
pub const LUA_RIDX_MAINTHREAD: lua_Integer = 1;
pub const LUA_RIDX_GLOBALS: lua_Integer = 2;
pub const LUA_RIDX_LAST: lua_Integer = LUA_RIDX_GLOBALS;

// Macro equivalents — C macros that bindgen cannot generate bindings for

#[inline(always)]
pub unsafe fn lua_upvalueindex(i: c_int) -> c_int {
    LUA_REGISTRYINDEX - i
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_call(L: *mut lua_State, n: c_int, r: c_int) {
    unsafe { lua_callk(L, n, r, 0, None) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_pcall(L: *mut lua_State, n: c_int, r: c_int, f: c_int) -> c_int {
    unsafe { lua_pcallk(L, n, r, f, 0, None) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_yield(L: *mut lua_State, n: c_int) -> c_int {
    unsafe { lua_yieldk(L, n, 0, None) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_tonumber(L: *mut lua_State, i: c_int) -> lua_Number {
    unsafe { lua_tonumberx(L, i, ptr::null_mut()) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_tointeger(L: *mut lua_State, i: c_int) -> lua_Integer {
    unsafe { lua_tointegerx(L, i, ptr::null_mut()) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_pop(L: *mut lua_State, n: c_int) {
    unsafe { lua_settop(L, -n - 1) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_newtable(L: *mut lua_State) {
    unsafe { lua_createtable(L, 0, 0) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_pushcfunction(L: *mut lua_State, f: lua_CFunction) {
    unsafe { lua_pushcclosure(L, f, 0) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_isfunction(L: *mut lua_State, n: c_int) -> c_int {
    unsafe { (lua_type(L, n) == LUA_TFUNCTION) as c_int }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_istable(L: *mut lua_State, n: c_int) -> c_int {
    unsafe { (lua_type(L, n) == LUA_TTABLE) as c_int }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_isnil(L: *mut lua_State, n: c_int) -> c_int {
    unsafe { (lua_type(L, n) == LUA_TNIL) as c_int }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_isboolean(L: *mut lua_State, n: c_int) -> c_int {
    unsafe { (lua_type(L, n) == LUA_TBOOLEAN) as c_int }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_pushliteral(L: *mut lua_State, s: &'static CStr) {
    unsafe {
        lua_pushstring(L, s.as_ptr());
    }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_tostring(L: *mut lua_State, i: c_int) -> *const c_char {
    unsafe { lua_tolstring(L, i, ptr::null_mut()) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_tolightuserdata(L: *mut lua_State, idx: c_int) -> *mut c_void {
    unsafe {
        if lua_type(L, idx) == LUA_TLIGHTUSERDATA {
            return lua_touserdata(L, idx);
        }
        ptr::null_mut()
    }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_insert(L: *mut lua_State, idx: c_int) {
    unsafe { lua_rotate(L, idx, 1) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_remove(L: *mut lua_State, idx: c_int) {
    unsafe {
        lua_rotate(L, idx, -1);
        lua_pop(L, 1)
    }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_replace(L: *mut lua_State, idx: c_int) {
    unsafe {
        lua_copy(L, -1, idx);
        lua_pop(L, 1)
    }
}

#[inline(always)]
pub unsafe fn lua_xpush(from: *mut lua_State, to: *mut lua_State, idx: c_int) {
    unsafe {
        lua_pushvalue(from, idx);
        lua_xmove(from, to, 1);
    }
}

// lua_error is blocklisted because it never returns — bindgen generates c_int return type
// which confuses Rust. We wrap it to return `!`.
unsafe extern "C-unwind" {
    #[link_name = "lua_error"]
    fn lua_error_(L: *mut lua_State) -> c_int;
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_error(L: *mut lua_State) -> ! {
    unsafe {
        lua_error_(L);
        core::hint::unreachable_unchecked()
    }
}

// lua_resume in Lua 5.3 takes 3 args; mlua expects the 5.4-style 4-arg version with nresults.
unsafe extern "C-unwind" {
    #[link_name = "lua_resume"]
    fn lua_resume_(L: *mut lua_State, from: *mut lua_State, narg: c_int) -> c_int;
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn lua_resume(
    L: *mut lua_State,
    from: *mut lua_State,
    narg: c_int,
    nresults: *mut c_int,
) -> c_int {
    unsafe {
        let ret = lua_resume_(L, from, narg);
        if (ret == LUA_OK || ret == LUA_YIELD) && !nresults.is_null() {
            *nresults = lua_gettop(L);
        }
        ret
    }
}

// lua_sethook takes a nullable hook — declare with Option<lua_Hook> so None can be passed.
unsafe extern "C-unwind" {
    pub fn lua_sethook(L: *mut lua_State, func: Option<lua_Hook>, mask: c_int, count: c_int);
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn luaL_loadbuffer(
    L: *mut lua_State,
    s: *const c_char,
    sz: usize,
    n: *const c_char,
) -> c_int {
    unsafe { luaL_loadbufferx(L, s, sz, n, ptr::null()) }
}

#[inline(always)]
#[allow(non_snake_case)]
pub unsafe fn luaL_loadbufferenv(
    L: *mut lua_State,
    data: *const c_char,
    size: usize,
    name: *const c_char,
    mode: *const c_char,
    mut env: c_int,
) -> c_int {
    unsafe {
        if env != 0 {
            env = lua_absindex(L, env);
        }
        let status = luaL_loadbufferx(L, data, size, name, mode);
        if status == LUA_OK && env != 0 {
            lua_pushvalue(L, env);
            lua_setupvalue(L, -2, 1);
        }
        status
    }
}
